HumanResources/Controllers/AccountManagementController.cs
using HumanResources.Models;
using HumanResources.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HumanResources.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AccountManagementController : Controller
    {
        IHRRepository _hRRepository;
        public AccountManagementController(IHRRepository hRRepository) 
        {
            _hRRepository = hRRepository;
        }
        [HttpGet]
        public IActionResult AddAccount()
        {
            AddAccountViewModel model = new AddAccountViewModel();
            return View(model);
        }
        [HttpPost]
        public IActionResult AddAccount(AddAccountViewModel model)
        {
            if (ModelState.IsValid)
            {
                SystemUserData data = new SystemUserData() { 
                    UserAccount = model.UserAccount, 
                    UserPassword = model.UserPassword,
                    UserAuth = model.UserAuth,
                    UserEmail = model.UserEmail,
                    UserName = model.UserName,
                    CreateTime = DateTime.Now,
                    LastModifiedBy = model.LastModifiedBy,
                    LastModifiedTime = DateTime.Now,
                    PasswordHash = null
                };

                var successed = _hRRepository.AddUserAccount(data);
                if (successed)
                {
                    return View();
                }
                else
                {
                    return View();
                }
            }
            else
            {
                return View();
            }
        }
    }
}

HumanResources/Controllers/HRSearchController.cs
using HumanResources.Data;
using HumanResources.Models;
using HumanResources.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HumanResources.Controllers
{
    [Authorize]
    public class HRSearchController : Controller
    {
        IHRRepository _hRRepository;
        public HRSearchController(IHRRepository hRRepository)
        {
            _hRRepository = hRRepository;
        }
        public IActionResult Search()
        {
            HRSearchViewModel model = new HRSearchViewModel();
            model.HumanResourcesMasters = _hRRepository.GetAllHRMasterData();
            model.Title = "人力資源總覽";
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            HumanResourcesMaster data = new HumanResourcesMaster();
            return View(data);
        }
        [HttpPost]
        public IActionResult Create(HumanResourcesMaster data)
        {
            var test = ModelState.Values;
            bool sucess = _hRRepository.AddHRMasterData(data);
            if (sucess)
            {
                return RedirectToAction("Search");
            }
            else
            {
                return View();
            }
        }
        [HttpGet]
        [Route("~/[controller]/[action]/{id?}")]
        public IActionResult Edit(int id)
        {
            HumanResourcesMaster data = new HumanResourcesMaster();
            data = _hRRepository.GetHRMasterDataByID(id);
            if (data == null)
            {
                Response.StatusCode = 404;
                return RedirectToAction("NotFound", "Error");
            }
            return View(data);
        }
        [HttpPost]
        public IActionResult Edit(HumanResourcesMaster data)
        {
            var sucess = _hRRepository.UpdateHRMasterData(data);
            if (sucess)
            {
                return RedirectToAction("Search");
            }
            else
            {
                return RedirectToAction("Edit",new { id = data.Id });
            }
        }
        [HttpGet]
        [Route("~/[controller]/[action]/{id?}")]
        public IActionResult Delete(int id)
        {
            var model = _hRRepository.GetHRMasterDataByID(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult Delete(HumanResourcesMaster data)
        {
            var sucess = _hRRepository.DeleteHRMasterData(data.Id);
            if (sucess)
            {
                return RedirectToAction("Search");
            }
            else
            {
                return RedirectToAction("Search");
            }
        }
    }
}

HumanResources/Controllers/LoginController.cs
using System.Security.Claims;
using HumanResources.Data;
using HumanResources.Models;
using HumanResources.ViewModels;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
namespace HumanResources.Controllers
{
    [Route("[Controller]")]
    public class LoginController : Controller
    {
        private readonly HumanResourcesContext _context;
        private readonly PasswordHasher<SystemUserData> passwordHasher;
        public LoginController(HumanResourcesContext context) 
        {
           _context = context;
        }
        [HttpGet]
        [Route("[Action]")]
        public IActionResult index(string errorCode) 
        {
            
            if (errorCode != null)
            {
                ViewBag.ErrorMessage = "密碼錯誤";
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ValidLogin(LoginModel loginData)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", new { errorCode = "error" });
            }
            else
            { 
                var list = (
                        from a in _context.SystemUserDatas
                        where a.UserAccount == loginData.uid & a.UserPassword == loginData.pwd
                        select new { a.UserAuth }
                        ).FirstOrDefault();
                if (list != null)
                {
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, loginData.uid)
                    };
                    // 根據用戶的角色來加入額外的 Claim
                    foreach (var role in list.UserAuth.Split(','))
                    {
                        claims.Add(new Claim(ClaimTypes.Role, role));
                    }
                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    //var authProperties = new AuthenticationProperties
                    //{
                    //    IsPersistent = loginData.RememberMe
                    //};

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                    return RedirectToAction("Index", "Home");
                }

                return RedirectToAction("Index", new { errorCode = "error" });
            }
        }
        // 這是處理登出的動作
        [HttpGet]
        [Route("[Action]")]
        public IActionResult logout()
        {
            return View(); // 登出後重定向到首頁
        }
        // 這是處理登出的動作
        [HttpPost]
        [Route("[Action]")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CheckLogout()
        {
            // 執行登出操作，清除用戶的身份驗證票證
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home"); // 登出後重定向到首頁
        }
    }
}

HumanResources/Views/Shared/_Layout.cshtml
@{
    var isAdmin = User.IsInRole("Admin");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HumanResources</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HumanResources.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HumanResources</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li> *@
                        <!-- 檢查用戶是否已登入 -->
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HRSearch" asp-action="Search">HR</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AccountManagement" asp-action="AddAccount">AccountManagement</a>
                        </li> *@
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                AccountManagement
                            </a>
                            <ul class="dropdown-menu">
                                @if (isAdmin)
                                {
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="AccountManagement" asp-action="AddAccount">AddAccount</a></li>
                                }
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - HumanResources - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>